GFVO_NS = "https://github.com/BioInterchange/Ontologies/gfvo#"
DCTERMS_NS = "http://purl.org/dc/elements/1.1/"
UNIPROT_NS = "http://purl.uniprot.org/core/"
SEQUENCE_ONTOLOGY_NS = "http://purl.obolibrary.org/obo/SO_"
FALDO_NS = "http://biohackathon.org/resource/faldo#"
# Internal namespaces
NS = "https://longseq.com/"
SAMPLE_NS = NS + "sample#"
CHROMOSOME_NS = NS + "chromosome#"
VARIANT_NS = NS + "variant#"
POSITION_NS = NS + "position#"
SEQUENCE_VARIANT_NS = NS + "alt#"
SEQUENCE_REFERENCE_NS = NS + "ref#"
GENOTYPE_NS = NS + "gt#"
LANDMARK_NS = NS + "landmark/"